# Generated by Django 5.2.1 on 2025-05-22 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('dashed', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fundamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('score', models.FloatField()),
                ('issuer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fundamental', to='App.issuer')),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r2_score', models.FloatField(blank=True, null=True)),
                ('mse', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('mape', models.FloatField(blank=True, null=True)),
                ('msle', models.FloatField(blank=True, null=True)),
                ('evs', models.FloatField(blank=True, null=True)),
                ('issuer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='App.issuer')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True)),
                ('title_al', models.CharField(blank=True, max_length=100, null=True)),
                ('title_mk', models.CharField(blank=True, max_length=100, null=True)),
                ('document_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('api', models.CharField(blank=True, max_length=100, null=True)),
                ('content_en', models.TextField(blank=True, null=True)),
                ('content_al', models.TextField(blank=True, null=True)),
                ('content_mk', models.TextField(blank=True, null=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='App.issuer')),
            ],
            options={
                'unique_together': {('issuer', 'date', 'document_id')},
            },
        ),
        migrations.CreateModel(
            name='NewsAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_id', models.CharField(max_length=100)),
                ('attachment_link', models.CharField(max_length=100)),
                ('file_name_en', models.CharField(max_length=100)),
                ('file_name_al', models.CharField(max_length=100)),
                ('file_name_mk', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='App.new')),
            ],
        ),
        migrations.CreateModel(
            name='Top_Issuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='top_issuer', to='App.issuer')),
            ],
        ),
        migrations.CreateModel(
            name='Last_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('issuer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_date', to='App.issuer')),
            ],
            options={
                'unique_together': {('issuer', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MovingAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(blank=True, choices=[('sma', 'Simple Moving Average'), ('ema', 'Exponential Moving Average'), ('wma', 'Weighted Moving Average'), ('hma', 'Hull Moving Average'), ('tema', 'Triple Exponential Moving Average')], max_length=30, null=True)),
                ('timeframe', models.CharField(blank=True, choices=[('1d', '1 Day'), ('1w', '1 Week'), ('1m', '1 Month')], max_length=3, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('signal', models.CharField(blank=True, max_length=20, null=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moving_averages', to='App.issuer')),
            ],
            options={
                'unique_together': {('issuer', 'indicator_type', 'timeframe', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Oscillator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(blank=True, choices=[('rsi', 'Relative Strength Index'), ('kvo', 'Klinger Volume Oscillator'), ('cci', 'Commodity Channel Index'), ('cmo', 'Chande Momentum Oscillator'), ('wpr', 'Williams %R')], max_length=30, null=True)),
                ('timeframe', models.CharField(blank=True, choices=[('14d', '14 Days')], max_length=3, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('signal', models.CharField(blank=True, max_length=20, null=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oscillators', to='App.issuer')),
            ],
            options={
                'unique_together': {('issuer', 'indicator_type', 'timeframe', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('avg', models.FloatField(blank=True, null=True)),
                ('chg', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('turnover', models.IntegerField(blank=True, null=True)),
                ('total_turnover', models.IntegerField(blank=True, null=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='App.issuer')),
            ],
            options={
                'unique_together': {('issuer', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('predicted_price', models.FloatField(blank=True, null=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='App.top_issuer')),
            ],
            options={
                'unique_together': {('issuer', 'date')},
            },
        ),
    ]
