# Generated by Django 5.2.1 on 2025-05-22 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Last_Date',
            new_name='LastDate',
        ),
        migrations.RenameModel(
            old_name='Top_Issuer',
            new_name='TopIssuer',
        ),
    ]
