# Generated by Django 5.2.1 on 2025-05-23 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_last_date_lastdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(blank=True, choices=[('sma', 'Simple Moving Average'), ('ema', 'Exponential Moving Average'), ('wma', 'Weighted Moving Average'), ('hma', 'Hull Moving Average'), ('tema', 'Triple Exponential Moving Average'), ('rsi', 'Relative Strength Index'), ('kvo', 'Klinger Volume Oscillator'), ('cci', 'Commodity Channel Index'), ('cmo', 'Chande Momentum Oscillator'), ('wpr', 'Williams %R')], max_length=30, null=True)),
                ('timeframe', models.CharField(blank=True, choices=[('1d', '1 Day'), ('1w', '1 Week'), ('1m', '1 Month'), ('14d', '14 Days')], max_length=3, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('signal', models.CharField(blank=True, max_length=20, null=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_indicators', to='App.issuer')),
            ],
            options={
                'unique_together': {('issuer', 'indicator_type', 'timeframe', 'date')},
            },
        ),
    ]
