# Generated by Django 5.2.1 on 2025-05-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_technicalindicator'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fundamental',
            constraint=models.UniqueConstraint(fields=('issuer',), name='unique_issuer_fundamental'),
        ),
    ]
