# Generated by Django 5.2.1 on 2025-05-23 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_prediction_issuer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='oscillator',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='oscillator',
            name='issuer',
        ),
        migrations.DeleteModel(
            name='MovingAverage',
        ),
        migrations.DeleteModel(
            name='Oscillator',
        ),
    ]
