# Generated by Django 5.2.1 on 2025-05-26 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_oscillator_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metrics',
            old_name='evs',
            new_name='max',
        ),
    ]
