# Generated by Django 5.2.1 on 2025-05-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_rename_evs_metrics_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsattachment',
            name='attachment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newsattachment',
            name='attachment_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newsattachment',
            name='file_name_al',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newsattachment',
            name='file_name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newsattachment',
            name='file_name_mk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newsattachment',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
