# Generated by Django 5.2.1 on 2025-05-28 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_newsattachment_attachment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastPredictionDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('issuer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_prediction_date', to='App.issuer')),
            ],
            options={
                'unique_together': {('issuer', 'date')},
            },
        ),
    ]
