# Generated by Django 5.2.1 on 2025-05-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_lastpredictiondate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lastdate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='lastpredictiondate',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='lastdate',
            constraint=models.UniqueConstraint(fields=('issuer',), name='unique_issuer_last_date'),
        ),
        migrations.AddConstraint(
            model_name='lastpredictiondate',
            constraint=models.UniqueConstraint(fields=('issuer',), name='unique_issuer_last_date_prediction'),
        ),
    ]
