# Generated by Django 5.2.1 on 2025-05-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_lastdate_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
